### ISSUE TITLE
Not taking effect

### ISSUE THREAD

**Issue by EraserKing** [Kr328/Riru-ClipboardWhitelist#1]
Xiaomi MIX 2S, MIUI 11 (Based on Android 10)

Riru Core 19.7
Riru Clipboard Whitelist v3
(Other Riru module, e.g. Storage Redirect is working well)

What I get from adb shell (seems the module is not loading the list correctly)
```polaris:/ $ su
polaris:/ # cat /data/misc/clipboard/whitelist.list
com.joaomgcd.join
polaris:/ # getprop sys.clipboard.whitelist
loaded
polaris:/ # exit```

**Comment by Taughtimp2786** [comment]
There might be an app named 'clipboard' in your app library. open that, and select the apps which you want clipboard acces.

**Comment by Taughtimp2786** [comment]
I am using the zygisk version, for me the `whitelist.list` file is located in `/data/system/zloader-s0aNjY2vxwip2ku2/zygisk_clipboard_whitelist/`
the folder might be `/data/system/zloader-[random strings]/zygisk_clipboard_whitelist/` for you (if you are using the zygisk version)
