### ISSUE TITLE
无法读取应用列表

### ISSUE THREAD

**Issue by Potat0000** [Kr328/Riru-ClipboardWhitelist#13]
Android 12
Android 安全更新：2022.1.5
ClipboardWhitelist v17

![Screenshot_2022-02-03-18-47-54-62_f81c13a31dd94da090ec8bd065cf04fa](https://user-images.githubusercontent.com/11223244/152328814-98308120-c972-463f-9f67-f09fa0342505.jpg)

**Comment by Potat0000** [comment]
> @Potat0000 我也有同样的问题，请问能说一下你是怎么解决的吗？

似乎是模块间的冲突。我关闭了一些模块后问题解决。

**Comment by freezewind** [comment]
> 

谢谢，我再排查一下
