### ISSUE TITLE
No access to clipboard after device reboot on v17 Android 10

### ISSUE THREAD

**Issue by bestexit** [Kr328/Riru-ClipboardWhitelist#14]
No access to clipboard after device reboot on v17 Android 10

**Comment by sky96111** [comment]
The same problem. On Android 11 with random Magisk package name and zygisk, the manager app lost configuration on every reboot.
While /data/system/zloader-xxx/zygisk_clipboard_whitelist/whitelist.list actually exists with configuration in it. It seems a bug with Manager app.
