### ISSUE TITLE
Potential result in CPU overload in V18

### ISSUE THREAD

**Issue by sky96111** [Kr328/Riru-ClipboardWhitelist#15]
### env
lineage_kebab-userdebug 11 RQ3A.211001.001 10039239
Magisk 24.1(24100) Zygisk
ClipboardWhitelist-zygisk V18
###

### screenshot
<details>
<summary>enable module htop</summary>

[![HUH4kn.png](https://s4.ax1x.com/2022/02/11/HUH4kn.png)](https://imgtu.com/i/HUH4kn)
</details>

<details>
<summary>disable module htop</summary>

[![HUH6l8.png](https://s4.ax1x.com/2022/02/11/HUH6l8.png)](https://imgtu.com/i/HUH6l8)
</details>

<details>
<summary>
Uncountable sum of SELinux avc errors, but maybe useless because I cannot catch them now</summary>

[![HUHzfx.png](https://s4.ax1x.com/2022/02/11/HUHzfx.png)](https://imgtu.com/i/HUHzfx)
</details>

### log
https://1drv.ms/u/s!AszSQqG8gUTQg9lJ7iMuL28xcAZClw?e=h4Dey1

**Comment by sky96111** [comment]
> [zygisk-clipboard-whitelist-v18.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8046704/zygisk-clipboard-whitelist-v18.zip)
> 
> try this build

Still have this problem. More and more zygiskd64 processes are created with time. Need I catch a new logcat for a longer time?

**Comment by sky96111** [comment]
logcat for about 1min.
I found that about 8 second, a new zygiskd64 process will be created
https://1drv.ms/u/s!AszSQqG8gUTQg9lKNyfNFbTCJMJ11Q?e=kkgxLr

**Comment by sky96111** [comment]
> [zygisk-clipboard-whitelist-v18.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8048661/zygisk-clipboard-whitelist-v18.zip)
> 
> Install and capture log again.
> 
> This build add some debug log only.

太奇怪了，用英文都难以描述...
装上第一版fix后还是会有CPU满载，于是我升级了Magisk到Canary版，问题依旧，我就禁用模块重启了。

刚刚看到GitHub的消息，装了debug版ClipboardWhitelist，重启竟然没有复现了。于是装回了fix 1版，重启竟然也没有复现
再退回Magisk到24.1也正常了。。现在还原了一切条件也没能复现之前的bug

我现在会保持fix1版观察一个晚上，如果不再次复现我会关掉这个issue。感谢！

**Comment by Kr328** [comment]
> > [zygisk-clipboard-whitelist-v18.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8048661/zygisk-clipboard-whitelist-v18.zip)
> > Install and capture log again.
> > This build add some debug log only.
> 
> 太奇怪了，用英文都难以描述... 装上第一版fix后还是会有CPU满载，于是我升级了Magisk到Canary版，问题依旧，我就禁用模块重启了。
> 
> 刚刚看到GitHub的消息，装了debug版ClipboardWhitelist，重启竟然没有复现了。于是装回了fix 1版，重启竟然也没有复现 再退回Magisk到24.1也正常了。。现在还原了一切条件也没能复现之前的bug
> 
> 我现在会保持fix1版观察一个晚上，如果不再次复现我会关掉这个issue。感谢！

有没有一种可能 我是说可能 第一个 build 是你刷错了

**Comment by sky96111** [comment]
> > > [zygisk-clipboard-whitelist-v18.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8048661/zygisk-clipboard-whitelist-v18.zip)
> > > Install and capture log again.
> > > This build add some debug log only.
> > 
> > 
> > 太奇怪了，用英文都难以描述... 装上第一版fix后还是会有CPU满载，于是我升级了Magisk到Canary版，问题依旧，我就禁用模块重启了。
> > 刚刚看到GitHub的消息，装了debug版ClipboardWhitelist，重启竟然没有复现了。于是装回了fix 1版，重启竟然也没有复现 再退回Magisk到24.1也正常了。。现在还原了一切条件也没能复现之前的bug
> > 我现在会保持fix1版观察一个晚上，如果不再次复现我会关掉这个issue。感谢！
> 
> 有没有一种可能 我是说可能 第一个 build 是你刷错了

好像真是这样（）
下载debug版的时候我嫌重名文件太多才全删掉重下了
