### ISSUE TITLE
Versions 19 and 20 (Riru)

### ISSUE THREAD

**Issue by bestexit** [Kr328/Riru-ClipboardWhitelist#17]
Versions 19 and 20 (Riru) do not work on android 10.
Версии 19 и 20 (Riru) не работают на 10 андроид.

---- 15 февр. 2022 г. 19:36:10 ----

02-15 19:33:27.222  1443  6886 I ActivityTaskManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.github.kr328.clipboard flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails bnds=[233,1578][811,1725]} from uid 10242

02-15 19:33:28.308 14950 14987 W Role    : com.github.kr328.clipboard not qualified for android.app.role.HOME due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.MAIN', mCategories='[android.intent.category.HOME]', mDataScheme='null', mDataType='null'}, mPermission='null', mMetaData=[]}

02-15 19:33:28.313 14950 14987 W Role    : com.github.kr328.clipboard not qualified for android.app.role.DIALER due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.DIAL', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='null', mMetaData=[]}

02-15 19:33:28.315 14950 15096 W Role    : com.github.kr328.clipboard not qualified for android.app.role.EMERGENCY due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.telephony.action.EMERGENCY_ASSISTANCE', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='null', mMetaData=[]}

02-15 19:33:28.318 14950 15096 W Role    : com.github.kr328.clipboard not qualified for android.app.role.SMS due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.provider.Telephony.SMS_DELIVER', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='android.permission.BROADCAST_SMS', mMetaData=[]}

02-15 19:34:21.472  1443  6734 I ActivityTaskManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.github.kr328.clipboard flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails bnds=[233,1425][811,1572]} from uid 10242

02-15 19:34:21.863 14950 14987 W Role    : com.github.kr328.clipboard not qualified for android.app.role.HOME due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.MAIN', mCategories='[android.intent.category.HOME]', mDataScheme='null', mDataType='null'}, mPermission='null', mMetaData=[]}

02-15 19:34:21.865 14950 14987 W Role    : com.github.kr328.clipboard not qualified for android.app.role.DIALER due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.DIAL', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='null', mMetaData=[]}

02-15 19:34:21.866 14950 14987 W Role    : com.github.kr328.clipboard not qualified for android.app.role.EMERGENCY due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.telephony.action.EMERGENCY_ASSISTANCE', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='null', mMetaData=[]}

02-15 19:34:21.867 14950 14987 W Role    : com.github.kr328.clipboard not qualified for android.app.role.SMS due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.provider.Telephony.SMS_DELIVER', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='android.permission.BROADCAST_SMS', mMetaData=[]}

---- 15 февр. 2022 г. 19:36:10 ----

**Comment by Kr328** [comment]
capture boot logs please

**Comment by bestexit** [comment]
[Log_2022-02-16_05-59-24.txt](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8076631/Log_2022-02-16_05-59-24.txt)

**Comment by bestexit** [comment]
[Log_2022-02-16_06-04-09.txt](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8076645/Log_2022-02-16_06-04-09.txt)

**Comment by Kr328** [comment]
The above logs do not contain any logs related to Riru or ClipboardWhitelist

please capture agint with https://github.com/RikkaApps/Riru/issues/236#issuecomment-875447977

**Comment by bestexit** [comment]
> The above logs do not contain any logs related to Riru or ClipboardWhitelist
> 
> please capture again with [RikkaApps/Riru#236 (comment)](https://github.com/RikkaApps/Riru/issues/236#issuecomment-875447977)

[Log_2022-02-16_07-25-23.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8077031/Log_2022-02-16_07-25-23.zip)

**Comment by bestexit** [comment]
> [zygisk-clipboard-whitelist-v20.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8094526/zygisk-clipboard-whitelist-v20.zip) [riru-clipboard-whitelist-v20.zip](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8094528/riru-clipboard-whitelist-v20.zip)
> 
> try this build

Checked version Riru , works fine.

**Comment by Neubulae** [comment]
The same occured to me and I just tested the Zygisk build here, fixed for me too.

**Comment by bestexit** [comment]
V 21Pre-release (riru) works fine.
