### ISSUE TITLE
v23、v21Clipboard程序不显示界面，无法使用

### ISSUE THREAD

**Issue by BlueDolphin9527** [Kr328/Riru-ClipboardWhitelist#22]
Realme GT Neo3 A30版本安卓12 面具24300 zygisk
第一次安装模块重启后，会先出现卡顿，点击桌面的图标，都不会打开，过个20秒左右才恢复正常。打开ClipBoard不显示界面，只有纯色背景。
ADB logcat捕捉：
[ClipBoard.log](https://github.com/Kr328/Riru-ClipboardWhitelist/files/8801425/ClipBoard.log)

**Comment by Kr328** [comment]
把 `/data/adb/modules/zygisk_clipboard_whitelist/system/app/ClipboardWhitelist/ClipboardWhitelist.apk` **剪切** 出来 重启之后自己安装 apk 试试
