### ISSUE TITLE
Not working on Android 13 P6P

### ISSUE THREAD

**Issue by aliantonio** [Kr328/Riru-ClipboardWhitelist#24]
Installed this module with Magisk v25.2 and Zygisk enabled. Enabled Join and Tasker in Clipboard app. Join doesn't appear to be picking up contents from the clipboard.

**Comment by DrSuSE** [comment]
Same here.  Tried with Riru core+Riru module+Zygisk disabled and Zygisk module+Zygisk enabled.  The Clipboard app shows up and everything LOOKS like it's working... just doesn't.

**Comment by tamas646** [comment]
Most probably duplicate of https://github.com/Kr328/Riru-ClipboardWhitelist/issues/30.
