### ISSUE TITLE
clipboard cannot be logged in android 13, logcat says: Denying clipboard access to xxx.xxxx.xxxx, application is not in focus nor is it a system service for user 0

### ISSUE THREAD

**Issue by GamerGirlandCo** [Kr328/Riru-ClipboardWhitelist#30]
i've tried reinstalling the module and unchecking and rechecking everything i want in the manager app. still doesn't work :/

**Comment by GamerGirlandCo** [comment]
[*they say, "if you want something done right, you'll always have to do it yourself"...*](https://github.com/GamerGirlandCo/xposed-clipboard-whitelist)

**Comment by Maxwellfire** [comment]
I have this same issue, but since you didn't fork this project, it's very hard to tell what you changed @GamerGirlandCo. If it's a fix to make this work on A13, maybe you could submit a pull request against this repository?

**Comment by GamerGirlandCo** [comment]
> I have this same issue, but since you didn't fork this project, it's very hard to tell what you changed @GamerGirlandCo. If it's a fix to make this work on A13, maybe you could submit a pull request against this repository?

it's an xposed module that hooks the newly added clipboardservice in android's framework and makes its [`clipboardAccessAllowed`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/clipboard/ClipboardService.java;drc=5148347352eadebb434d1bc1f18305647add609d;bpv=1;bpt=1;l=1043?q=denying%20clipboard%20access%20&gsn=clipboardAccessAllowed&gs=kythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Djava%3Fpath%3Dcom.android.server.clipboard.ClipboardService%234b41c7fdd5032ec20dfe5c371d288ae8428e9bc80e812347bb70b1a6e2c0ef1d)` method return true. idk how to make this work with zygisk though...

**Comment by tamas646** [comment]
Same issue on LOS 20 (Android 13).

Error: `Denying clipboard access to <package_name>, application is not in focus nor is it a system service for user <user_id>`

**Comment by tamas646** [comment]
I tried the xposed module modified by @GamerGirlandCo, but for me it's still not working.

Previously I used the zygisk version of this module on LOS 19 (Android 12) which worked fine.
Now I updated to LOS 20 and the module stopped working (with the error above).

I disabled the zygisk module in Magisk, installed the modified xposed module (with LSPosed), then rebooted.
The issue still persists, the fix did not help. :(

The app I'm trying to use: KDE Connect

**Comment by GamerGirlandCo** [comment]
@tamas646 try the latest release or some shit like that. should work since i'm hooking both methods instead of just one

**Comment by tamas646** [comment]
@GamerGirlandCo still not working with version 1.1 either

**Comment by GamerGirlandCo** [comment]
> @GamerGirlandCo still not working with version 1.1 either

this is probably a stupid question but, have you selected "System Framework" for the module scope?

**Comment by tamas646** [comment]
No, I selected "KDE Connect". Selecting "System Framework" and rebooting solved my problem. Thanks.

(Sorry, I never used this module with XPOSED, only with Magisk which doesn't need selecting anything. But thanks again for the tip)

**Comment by tamas646** [comment]
As @Maxwellfire suggested it would be great if you could submit a pull request. :)
Thanks for the fix.
