### ISSUE TITLE
升级到 v24 导致 miui13 系统崩溃

### ISSUE THREAD

**Issue by deltazefiro** [Kr328/Riru-ClipboardWhitelist#31]
您好。我将模块升级到 v24 导致系统启动后立刻崩溃，使用 v23 不会出现此问题。
崩溃前系统提示 miui Permission 停止运行，随后系统停止运行并自动关机。
由于系统开机后立刻崩溃，尚未抓取 log。若有需要稍晚些附上。
谢谢。

相关信息：
- system: miui 13.0.13.1 (Android 12)
- magisk: 25.2 (25200), zygisk
- clipboard whitelist: v24

**Comment by Kr328** [comment]
传个开机的 logcat 日志把

**Comment by deltazefiro** [comment]
感谢回复。抱歉，似乎并非此模块的问题。:thinking:
今天尝试若仅启用此模块并不会出现问题。只有与 LSPosed (及其中的模块) 同时启用时才会导致 Permission 停止运行，但也并未出现系统崩溃。疑似与某个 lsp 模块冲突。我会尝试排查是哪个模块，并去对应的模块反馈问题。
[与 lsposed 同时启用后 miui Permission 崩溃的 log](https://github.com/Kr328/Riru-ClipboardWhitelist/files/10798896/perm_crash.log)

**Comment by deltazefiro** [comment]
感谢回复。抱歉，似乎并非此模块的问题。:thinking:
今天尝试若仅启用此模块并不会出现问题。只有与 LSPosed (及其中的模块) 同时启用时才会导致 Permission 停止运行，但也并未出现系统崩溃。疑似与某个 lsp 模块冲突。我会尝试排查是哪个模块，并去对应的模块反馈问题。
[与 lsposed 同时启用后 miui Permission 崩溃的 log](https://github.com/Kr328/Riru-ClipboardWhitelist/files/10798972/perm_crash.log)

**Comment by Kr328** [comment]
上传一下在 LSP **启用**的时候 `/data/adb/modules/zygisk_clipboard_whitelist/module.prop` 文件

**Comment by deltazefiro** [comment]
```
# Generated by ZygoteLoader. DO NOT EDIT.
version=v24
versionCode=24
minSdkVersion=29
id=zygisk_clipboard_whitelist
name=Zygisk - Clipboard Whitelist
archiveName=zygisk-clipboard-whitelist-v24
updateJson=https://github.com/Kr328/Riru-ClipboardWhitelist/releases/latest/download/zygisk-clipboard-whitelist.json
author=Kr328
description=Allow apps access clipboard in background.
entrypoint=com.github.kr328.clipboard.Main
useBinderInterceptors=true
dataDirectory=/data/system/zloader-zK1YBUsfpHkvh0hm/zygisk_clipboard_whitelist
```
