### ISSUE TITLE
No App Installed

### ISSUE THREAD

**Issue by DrSuSE** [Kr328/Riru-ClipboardWhitelist#32]
I installed the Zygisk version on my Pixel 7 Pro, Android 13.

No clipboard or whitelist app was installed, so there's no way to configure this.  It is listed in the Modules section of Magisk.  Rebooted after install, etc etc.

I confirmed it's also not just somehow magically working.  What can I do?

**Comment by DrSuSE** [comment]
Don't auto close

**Comment by Xander-C** [comment]
you can try to edit `/data/misc/clipboard/whitelist.list` manually, one package name per line. 
(or check if that file exists)

**Comment by DrSuSE** [comment]
@Xander-C I did manage to get it installed (I think it was actually a bug in the version of Magisk Canary I had running) but even after adding Join (https://play.google.com/store/apps/details?id=com.joaomgcd.join) to the whitelist app, the clipboard sync'ing didn't work.
