### ISSUE TITLE
模块在Android 13, Magisk 26.1不起作用

### ISSUE THREAD

**Issue by entr0pia** [Kr328/Riru-ClipboardWhitelist#36]
版本:
- zygisk-ClipboardWhitelist: v24
- 系统: LineageOS 20
- 设备: Xperia 5II
- Magisk: 26.1
- 目标应用: KDE Connect 1.25.0

症状:

尝试重装ClipboardWhitelist, 重装KDE Connect, 主动唤醒ClipboardWhitelist root权限(我忘记了低版本时的会不会自动申请权限).
模块可正常在`/data/system/zloader-QZpY2Q5paxFVZauj/zygisk_clipboard_whitelist/whitelist.list`生成配置文件, 但KDE Connect,就是无法从后台读取剪贴板

**Comment by Typhonling** [comment]
跟你一模一样的环境，也是为了使用KDE Connect，自从升上Android 13就无法正常使用了。只是懒得发issues。

**Comment by entr0pia** [comment]
> Oneplus 8 pro 跟你一模一样的环境，也是为了使用KDE Connect，自从升上Android 13就无法正常使用了。只是懒得发issues。 具体症状是KDE无法自动同步剪贴板，使用系统分享菜单手动分享也失效。只能从KDE通知栏/快速磁贴/KDE本体手动发送剪贴板，快速磁贴应该是最方便的临时替代方案了。

v21能用

**Comment by Typhonling** [comment]
> > Oneplus 8 pro 跟你一模一样的环境，也是为了使用KDE Connect，自从升上Android 13就无法正常使用了。只是懒得发issues。 具体症状是KDE无法自动同步剪贴板，使用系统分享菜单手动分享也失效。只能从KDE通知栏/快速磁贴/KDE本体手动发送剪贴板，快速磁贴应该是最方便的临时替代方案了。
> 
> v21能用

试了，不行。

**Comment by entr0pia** [comment]
> > > Oneplus 8 pro 跟你一模一样的环境，也是为了使用KDE Connect，自从升上Android 13就无法正常使用了。只是懒得发issues。 具体症状是KDE无法自动同步剪贴板，使用系统分享菜单手动分享也失效。只能从KDE通知栏/快速磁贴/KDE本体手动发送剪贴板，快速磁贴应该是最方便的临时替代方案了。
> > 
> > 
> > v21能用
> 
> 试了，不行。

app本身也要降级到v21

**Comment by Typhonling** [comment]
> > > > Oneplus 8 pro 跟你一模一样的环境，也是为了使用KDE Connect，自从升上Android 13就无法正常使用了。只是懒得发issues。 具体症状是KDE无法自动同步剪贴板，使用系统分享菜单手动分享也失效。只能从KDE通知栏/快速磁贴/KDE本体手动发送剪贴板，快速磁贴应该是最方便的临时替代方案了。
> > > 
> > > 
> > > v21能用
> > 
> > 
> > 试了，不行。
> 
> app本身也要降级到v21

并没有手动安装过apk，app版本和模块一致。
结论是仍然无效。

**Comment by Typhonling** [comment]
奇怪了，经过测试，通过剪贴板快捷方式分享到KDE的文本为网址的话，Windows端会自动打开网页，但仍旧不会覆盖剪贴板内容。
将尝试测试其他剪贴板同步软件。

**Comment by Typhonling** [comment]
https://www.reddit.com/r/tasker/comments/wpt39b/dev_warning_if_you_update_to_android_13_the/

Clipboard Monitoring on Android 13 also works by monitoring the Logcat so that won't work either unfortunately.

Since Join also uses the same technique for clipboard monitoring, syncing the clipboard from phone to PC will stop working as well with Join.

也许原因在这里。

**Comment by Typhonling** [comment]
搜索 android 13 logcat clipboard 也许能得到答案，应该是与logcat有关。

**Comment by Typhonling** [comment]
没有及时检查其他issues是我的失误，#30 中的xposed模块很好的解决了问题。
有个小问题是它仅需要勾选系统框架即能全局生效，需配合xprivacy阻止其他应用后台读取剪贴板。

**Comment by Typhonling** [comment]
V26仍旧未解决无法自动后台读取剪贴板的问题，继续使用xposed模块将就。

**Comment by entr0pia** [comment]
Android 14彻底用不了, 我修改了上文中的Xposed模块, 它现在仅对KDE Connect生效: [Release v1.2.1 · entr0pia/xposed-clipboard-whitelist](https://github.com/entr0pia/xposed-clipboard-whitelist/releases/tag/v1.2.1)

**Comment by Anderhar** [comment]
> Android 14彻底用不了, 我修改了上文中的Xposed模块, 它现在仅对KDE Connect生效: [Release v1.2.1 · entr0pia/xposed-clipboard-whitelist](https://github.com/entr0pia/xposed-clipboard-whitelist/releases/tag/v1.2.1)

Does your module grant access exclusively to KDE Connect, or opens clipboard in background to all installed apps? Asking because [KingGoldXu's fork](https://github.com/KingGoldXu/xposed-clipboard-whitelist) provides whitelist option, although this is redundant if used only with KDE Connect (while your solution works right out of the box).

**Comment by entr0pia** [comment]
> > Android 14彻底用不了, 我修改了上文中的Xposed模块, 它现在仅对KDE Connect生效: [Release v1.2.1 · entr0pia/xposed-clipboard-whitelist](https://github.com/entr0pia/xposed-clipboard-whitelist/releases/tag/v1.2.1)
> 
> Does your module grant access exclusively to KDE Connect, or opens clipboard in background to all installed apps? Asking because [KingGoldXu's fork](https://github.com/KingGoldXu/xposed-clipboard-whitelist) provides whitelist option, although this is redundant if used only with KDE Connect (while your solution works right out of the box).

Yes, I have only granted background clipboard access for KDE Connect.

**Comment by Typhonling** [comment]
此项目的另一个fork在A15上完美使用，并不只受限于kdeconnect，可自由选择生效的应用。因为除了kdeconnect，输入法也需要后台读取剪切板的能力，以保存历史剪切板列表。https://github.com/KingGoldXu/xposed-clipboard-whitelist
