### ISSUE TITLE
Tap to translate doesnt work

### ISSUE THREAD

**Issue by mclongthanh** [Kr328/Riru-ClipboardWhitelist#6]
After install newest core+module, then add Google Translate to Clipboard whitelist app (even reboot more time), Tap to Translate does not work same as android 9 (android 9: appear bubble once copying any text on any app). it means Google Translate dont have right to access clipboard in background

**Comment by Kr328** [comment]
Google Translate does not access the clipboard and not start 'Tap to Translate' service in the background on Android 10+

This module cannot change the app behavior, it can only make an attempt to access a denied operation successful.
